# Generated by Django 4.1.1 on 2022-10-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=64)),
                ('bio', models.TextField()),
                ('image', models.CharField(max_length=128)),
            ],
        ),
    ]
