# Generated by Django 4.1.1 on 2022-10-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_crewmember_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crewmember',
            options={'verbose_name_plural': 'Crew Members'},
        ),
    ]
