# Generated by Django 4.1.4 on 2022-12-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0003_alter_crewmember_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
