# Generated by Django 4.1.1 on 2022-10-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('portrait_image', models.CharField(max_length=128)),
                ('landscape_image', models.CharField(max_length=128)),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
