# Generated by Django 4.1.4 on 2022-12-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0002_alter_technology_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='landscape_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='technology',
            name='portrait_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
